# Use environment variables
#production:
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
#
# or specify values manually
 production:
   host: localhost
   port: 27017
   username:
   password:
   database: graylog2

# Values below are for development and testing.
# You may comment out them or just ignore.
#
#development:
#  host: localhost
#  database: graylog2_development
#
#test:
#  host: localhost
#  database: graylog2_test
